.github/pull_request_template.md
Fix #7 
Test URLs:
- After: https://issue-7--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> fix github issue template

scripts/scripts.js
Adds launch script which inits google tag manager
Have done some tests, doesn't seem to be any different running this here vs in delayed.
Test URLs:
- After: https://add-launch-script--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Add launch script

blocks/cards/cards.css, blocks/cards/cards.js, blocks/columns/columns.css, blocks/hero-column/hero-column.css, blocks/hero-column/hero-column.js, styles/styles.css
Fix #10 
Test URLs:
- Before: https://main--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market.html
- After: https://issue-10--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Main section final

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Fix #
Test URLs:
- After: https://header-2--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Header changes

blocks/header/header.css, blocks/header/header.js
Fix #23 
Test URLs:
- After: https://header-1-level--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Adding 1-level header dropdown changes

blocks/header/header.js
Fix #26
Test URLs:
- After: https://nav-close-button--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
Close button added in PR https://github.com/aemsites/phoenix/pull/25
=> Updating close button in Nav dropdown

blocks/header/header.js, styles/styles.css
Fix #28 
Test URLs:
- After: https://issue-28--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> No Scroll on Nav dropdown open

styles/styles.css
Hide chat widget on small devices
Test URLs:
- After: https://contact-widgets--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Hide chat widget on small devices

blocks/accordion/accordion.css, blocks/header/header.css, blocks/hero-column/hero-column.css, scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://anav--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Fix Aside nav and add request info button 

blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/newsletter-form.js, blocks/newsletter-form/newsletter-form.css
Test URLs:
- After: https://footer--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> added form

blocks/footer/footer.css, blocks/footer/footer.js
Test URLs:
- Before: https://main--phoenix--aemsites.hlx.live/
- After: https://<branch>--phoenix--aemsites.hlx.live/
=> fix:(footer) improved mobile view, added bottom footer links

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Fix #22
Test URLs:
- After: https://issue-22--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Dropdown Container for "Admission Tuitions" & "About" Nav (2-level container) for desktop view

blocks/header/header.js
Test URLs:
- After: https://search-close-fix-mobile--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Search close button fix

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Test URLs:
- After: https://mobile-header--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Mobile header

blocks/header/header.css
Fix #40
Test URLs:
- After: https://issue-40--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> fix: Font size breaking for nav section when width >= 1300 and scroll to bottom

blocks/header/header.css, blocks/header/header.js
Fix #42
Test URLs:
- After: https://issue-42--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> ‘Take a Single Course’ handling for "Online Degrees & Courses"

blocks/article-header/article-header.css, blocks/header/header.css, blocks/hero/hero.css
Test URLs:
- After: https://search-link-update--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Search link update

blocks/accordion/accordion.css, blocks/article-header/article-header.css, blocks/columns/columns.css, styles/styles.css
Test URLs:
- After: https://polisihing-style--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Polisihing style

blocks/header/header.css
Test URLs:
- After: https://polish-styling-absarasw--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Making header background translucent for the article content

blocks/header/header.css, blocks/header/header.js
Test URLs:
- After: https://polish-styling-absarasw--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Polish styling absarasw

blocks/article-header/article-header.css, blocks/article-header/article-header.js, styles/styles.css
Test URLs:
- After: https://sfix--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> fix: main and aside gap, social icons

blocks/article-header/article-header.css, scripts/delayed.js, scripts/scripts.js
Test URLs:
- After: https://lhs-check--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Moving launch script load to delayed.js

blocks/accordion/accordion.css, blocks/article-header/article-header.css, scripts/scripts.js, styles/styles.css
Test URLs:
- After: https://anav-5--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Aside nav final

blocks/accordion/accordion.css, styles/styles.css
Test URLs:
- After: https://anav-6--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Main styling fixes

blocks/header/header.css, blocks/header/header.js
* Call icon fix
* Added animation in header on load
Fix #74 
Fix #75 
Test URLs:
- After: https://call-icon-fix--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Call icon fix and Header animation on load

styles/styles.css
Test URLs:
- After: https://cookies-fix--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Cookies banner fix for mobile view

blocks/cards/cards.css
Fix #86 
Test URLs:
- After: https://issue-86--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Updating grid wrap behavior for read more card block

aem/blocks/hero/hero.js, aem/styles/styles.css
* removing lint errors
Test URLs:
- After: https://hero-image-eager-load--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Eager loading hero image

aem/scripts/delayed.js, aem/styles/styles.css
Test URLs:
- After: https://footer-1--phoenix--aemsites.hlx.live/blog/how-to-prepare-for-an-unpredictable-job-market
=> Sticky footer fix
